worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream api_backend {
        server api:8000;
    }

    upstream mlflow_backend {
        server mlflow:5000;
    }

    upstream evidently_backend {
        server evidently:8050;
    }

    server {
        listen 80;

        # API de prédiction (défaut)
        location / {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Interface MLflow
        location /mlflow/ {
            rewrite ^/mlflow/(.*) /$1 break;
            proxy_pass http://mlflow_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Rapports de monitoring Evidently
        location /monitoring/ {
            rewrite ^/monitoring/(.*) /$1 break;
            proxy_pass http://evidently_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
